### ISSUE TITLE
Blink with timer/interrupts

### ISSUE THREAD

**Issue by AdyiPool** [redbear/WICED-SDK#5]
Hello,

 Thanks for the great examples with the WICED SDK here. In addition to the blink example, can you provide something similar that does not use `wiced_rtos_delay_milliseconds()`. I would rather like to have a task called using timers/interrupts, rather than a `while(1)` loop

**Comment by Cheong2K** [comment]
Hi, I think it is better to post this in Cypress WICED SDK forum.
https://community.cypress.com/welcome

**Comment by JacksonLv** [comment]
hi @AdyiPool : 
Please read the include/wiced_rtos.h file ,you will find the API you want.

**Comment by AdyiPool** [comment]
Thanks, this example was helpful: https://community.cypress.com/community/wiced-wifi/wiced-wifi-forums/blog/2016/05/18/simple-usage-of-timers
